//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace md2html.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("md2html.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bug, unhandled exception: {0}
        ///{1}.
        /// </summary>
        internal static string BugMessage {
            get {
                return ResourceManager.GetString("BugMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to directive name must be separated from the double-at symbols by exactly one space, at {0}#{1}: {2}.
        /// </summary>
        internal static string DirectiveNameMustFollowSingleSpaceErrorMessage {
            get {
                return ResourceManager.GetString("DirectiveNameMustFollowSingleSpaceErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to error: {0}.
        /// </summary>
        internal static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown directive &apos;{0}&apos;, at {1}#{2}: {3}.
        /// </summary>
        internal static string UnknownDirectiveErrorMessage {
            get {
                return ResourceManager.GetString("UnknownDirectiveErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usage: md2html [-option(s)] input-filename [output-filename]
        ///options:
        ///  -h, --help      This help text.
        ///  -v, --verbose   Enable verbose output..
        /// </summary>
        internal static string HelpText {
            get {
                return ResourceManager.GetString("HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to input file {0}, or part of its path does not exist ({1}).
        /// </summary>
        internal static string InputFileNotFoundErrorMessage {
            get {
                return ResourceManager.GetString("InputFileNotFoundErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no file(s) specified, nothing to do.
        /// </summary>
        internal static string NothingToDoMessage {
            get {
                return ResourceManager.GetString("NothingToDoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to recursive inclusion of Markdown source file &apos;{0}&apos;.
        /// </summary>
        internal static string RecursiveFileInclusionErrorMessage {
            get {
                return ResourceManager.GetString("RecursiveFileInclusionErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to too many filenames specified: {0}.
        /// </summary>
        internal static string TooManyFilesErrorMessage {
            get {
                return ResourceManager.GetString("TooManyFilesErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unable to process action {0}.
        /// </summary>
        internal static string UnableToProcessActionErrorMessage {
            get {
                return ResourceManager.GetString("UnableToProcessActionErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unable to determine what to do.
        /// </summary>
        internal static string UnknownActionErrorMessage {
            get {
                return ResourceManager.GetString("UnknownActionErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown option: {0}.
        /// </summary>
        internal static string UnknownOptionErrorMessage {
            get {
                return ResourceManager.GetString("UnknownOptionErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to md2html v{0}, MarkdownSharp v{1}.
        /// </summary>
        internal static string VersionMessageWithMarkdown {
            get {
                return ResourceManager.GetString("VersionMessageWithMarkdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to md2html v{0}.
        /// </summary>
        internal static string VersionMessageWithoutMarkdown {
            get {
                return ResourceManager.GetString("VersionMessageWithoutMarkdown", resourceCulture);
            }
        }
    }
}
